### ISSUE TITLE
Please package 0.14.x

### ISSUE THREAD

**Issue by knowledgejunkie** [codehelp/pkg-pyocd-dfsg#1]
I'm currently packaging the mbed-host-tests (part of the yotta dependency chain in order to build MicroPython for the micro:bit) which requires the pyocd.flash.loader module added in 0.14.x

**Comment by codehelp** [comment]
Sorry, I am no longer able to work on packaging. The Debian pyocd package is orphaned, waiting for someone else to take over maintenance.
https://bugs.debian.org/976075
https://tracker.debian.org/pkg/pyocd
